release_testutils.yml - update runner to macos and add version format validation

diff --git a/.github/workflows/release_testutils.yml b/.github/workflows/release_testutils.yml
--- a/.github/workflows/release_testutils.yml
+++ b/.github/workflows/release_testutils.yml
@@ -9,9 +9,18 @@ on:
 
 jobs:
   release-testutils:
-    runs-on: ubuntu-latest
+    runs-on: macos-latest
 
-    steps:    
+    steps:
+    - name: Validate Version Format
+      id: validate_version
+      run: |
+        if [[ ! "${{ github.event.inputs.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+          echo "Error: Version format is invalid. Expected format: x.y.z"
+          exit 1
+        fi
+        echo "Version format is valid."
+    
     - name: Checkout
       uses: actions/checkout@v4.1.7
 
